import { drizzle } from 'drizzle-orm/node-postgres';
import { currenciesTable } from '../schema/currencies.schema';
import dotenv from 'dotenv';
import { gamesTable } from '../schema/games.schema';
dotenv.config();

const db = drizzle(process.env.DATABASE_URL!);

const data = [
  {
    id: '85813742-6c61-45cc-8815-909fa270df47',
    slug: 'Hot Seven',
    name: 'Hot Seven',
    provider: 'amatic',
    providerGameId: '340',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/888_Hot7.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '3628857c-834a-4cc7-a0a2-e2d0b70bdf2b',
    slug: 'Mega Shark',
    name: 'Mega Shark',
    provider: 'amatic',
    providerGameId: '6909',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/MegaShark.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '0e4f1ae0-3c4b-4f92-95c5-9dad04a94cbc',
    slug: 'Party Night',
    name: 'Party Night',
    provider: 'amatic',
    providerGameId: '4581',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/PartyNight.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '83045c5b-54d7-4a76-92f7-2a265a6e6cc4',
    slug: 'Hot Choice',
    name: 'Hot Choice',
    provider: 'amatic',
    providerGameId: '4217',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotChoice.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'a4af1c0c-a748-405b-9019-88ddf6303fd4',
    slug: 'Enchanted Cleopatra',
    name: 'Enchanted Cleopatra',
    provider: 'amatic',
    providerGameId: '4212',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/EnchantedCleopatra.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '940bce75-42c1-4a69-8a55-10290a9ae801',
    slug: 'Red Chilli',
    name: 'Red Chilli',
    provider: 'amatic',
    providerGameId: '3097',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/862_RedChilli.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '99f037f2-d5b8-4eea-9a58-87b3e5f71d10',
    slug: 'Wild Dragon',
    name: 'Wild Dragon',
    provider: 'amatic',
    providerGameId: '3064',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/WildDragon.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'feb934cd-1d48-4b12-9757-7afb92534e7e',
    slug: 'Diamond Cats',
    name: 'Diamond Cats',
    provider: 'amatic',
    providerGameId: '364',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/776_DiamondCats.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ef2f8cb1-cd04-41c9-8784-eeb8aabaf033',
    slug: 'Dragons Pearl',
    name: 'Dragons Pearl',
    provider: 'amatic',
    providerGameId: '357',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/746_DragonsPearl.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'bf5e3ae7-c627-4398-a686-3640e78294cd',
    slug: 'Lucky Bells',
    name: 'Lucky Bells',
    provider: 'amatic',
    providerGameId: '345',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/777_LuckyBells.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'dbbee486-833d-4d03-b9c1-95d6bf1df349',
    slug: 'Wild 7',
    name: 'Wild 7',
    provider: 'amatic',
    providerGameId: '339',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/740_Wild7.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '3c38fab6-4486-422e-81f3-bad215e3fc7b',
    slug: 'Hot Scatter',
    name: 'Hot Scatter',
    provider: 'amatic',
    providerGameId: '350',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/751_HotScatter.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '62483a89-7cbb-4c46-b1b0-2a996bd92fd2',
    slug: 'Fire Queen',
    name: 'Fire Queen',
    provider: 'amatic',
    providerGameId: '7696',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/FireQueen.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '3616f2e7-26ad-420b-a783-db33b0e522b5',
    slug: 'Grand Fruits',
    name: 'Grand Fruits',
    provider: 'amatic',
    providerGameId: '10498',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/GrandFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '7630f9fa-df54-4269-930f-e8ce879e17fe',
    slug: 'Wild Shark Bonus Buy',
    name: 'Wild Shark Bonus Buy',
    provider: 'amatic',
    providerGameId: '10497',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/wildsharkbonusbuy.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '7365be86-3ac4-4dc3-958b-2951c98ef5af',
    slug: 'Lady Fruits 40 Easter',
    name: 'Lady Fruits 40 Easter',
    provider: 'amatic',
    providerGameId: '8880',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LadyFruits40easter.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '24245d22-b84d-4665-9602-e138af4e2517',
    slug: 'Burning Bells 40',
    name: 'Burning Bells 40',
    provider: 'amatic',
    providerGameId: '8877',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BurningBells40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '9e62b5c3-0d17-43db-a8c8-93f622557b0c',
    slug: 'Hottest Fruits 40',
    name: 'Hottest Fruits 40',
    provider: 'amatic',
    providerGameId: '7699',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HottestFruits40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '9d752c70-ef64-47c7-a129-230f77a4c815',
    slug: 'All Ways Hot Fruits',
    name: 'All Ways Hot Fruits',
    provider: 'amatic',
    providerGameId: '7697',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/AllWaysHotFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '68d0cb96-875a-4f2c-9605-d8dc2be2d83d',
    slug: 'Hot Scatter Deluxe',
    name: 'Hot Scatter Deluxe',
    provider: 'amatic',
    providerGameId: '6897',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotScatterDeluxe.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '1d74a04d-bc47-47e8-a3bb-b8692392fe06',
    slug: 'Golden Quest',
    name: 'Golden Quest',
    provider: 'amatic',
    providerGameId: '6901',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/GoldenQuest.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c986654f-7ceb-4c2e-86ce-a24ec80e8709',
    slug: 'Magic Scatter',
    name: 'Magic Scatter',
    provider: 'amatic',
    providerGameId: '4268',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/MagicScatter.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '2f5b6935-7c92-420d-8de7-8632559147ed',
    slug: 'Hot 40',
    name: 'Hot 40',
    provider: 'amatic',
    providerGameId: '4266',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/Hot40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c5106706-568a-4464-b5d5-beb68ef1814e',
    slug: 'Joker Card Poker',
    name: 'Joker Card Poker',
    provider: 'amatic',
    providerGameId: '3160',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/JokerCardPoker.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '075620e4-9291-4a42-9eca-9872648873c1',
    slug: 'Ultra Seven',
    name: 'Ultra Seven',
    provider: 'amatic',
    providerGameId: '4211',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/UltraSeven.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '7f214c99-0cf4-4283-8406-7834acb9e7f7',
    slug: 'Fantastico',
    name: 'Fantastico',
    provider: 'amatic',
    providerGameId: '3119',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/865_Fantastico.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ab043126-6ed8-4ce1-b0b3-c71b0c7e95b4',
    slug: 'Lovely Lady',
    name: 'Lovely Lady',
    provider: 'amatic',
    providerGameId: '3112',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LadyLuck2.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4caf3451-3ae2-4db9-84af-afcb1a699bb2',
    slug: 'Bells on Fire Hot',
    name: 'Bells on Fire Hot',
    provider: 'amatic',
    providerGameId: '3091',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/789_BellsOnFireHot.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '43238638-a62e-446c-b230-5734d9dd73c7',
    slug: 'Casinova',
    name: 'Casinova',
    provider: 'amatic',
    providerGameId: '3089',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/781_Casinova.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '48f6d114-56c3-4d3f-9ece-a9a8df304c69',
    slug: 'Grand Tiger',
    name: 'Grand Tiger',
    provider: 'amatic',
    providerGameId: '3062',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/GrandTiger.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'a54fbb30-c958-4e67-9a59-99199943e6b9',
    slug: 'Diamond Monkey',
    name: 'Diamond Monkey',
    provider: 'amatic',
    providerGameId: '3053',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/795_DiamondMonkey.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'dabb6ccf-fcec-4490-88d5-0c30a6ceea6a',
    slug: 'Dragons Kingdom',
    name: 'Dragons Kingdom',
    provider: 'amatic',
    providerGameId: '3026',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/784_DragonsKingdom.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c2b3272f-1a1e-4a2f-b812-5f8d4e41eba0',
    slug: 'Roman Legion',
    name: 'Roman Legion',
    provider: 'amatic',
    providerGameId: '365',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/780_RomanLegion.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'e0f236fd-9b70-4aa8-8dfb-f83cda28bbe0',
    slug: 'Hot Diamonds',
    name: 'Hot Diamonds',
    provider: 'amatic',
    providerGameId: '362',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/764_HotDiamonds.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'dcda890e-2e34-481a-8b38-b1ec67ed5595',
    slug: 'Lucky Zodiac',
    name: 'Lucky Zodiac',
    provider: 'amatic',
    providerGameId: '352',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/817_luckyzodiacc.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'e9daee23-c4c6-455e-91ba-790d830af5aa',
    slug: 'Hot Neon',
    name: 'Hot Neon',
    provider: 'amatic',
    providerGameId: '353',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/752_HotNeon.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd9034e82-b355-400d-8896-a5badbe439b6',
    slug: 'Fortunas Fruits',
    name: 'Fortunas Fruits',
    provider: 'amatic',
    providerGameId: '343',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/761_FortunasFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '2c4e2a64-9cea-4c15-a6d4-0d46b5c98fec',
    slug: 'Hot 27',
    name: 'Hot 27',
    provider: 'amatic',
    providerGameId: '342',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/744_TwentySeven.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '7ad6657b-65f4-436e-8efc-95c0b10324ff',
    slug: 'Wild Diamonds',
    name: 'Wild Diamonds',
    provider: 'amatic',
    providerGameId: '298',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/WildDiamonds.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c3bb0f6f-b791-4720-b6d7-cf698ca6e51e',
    slug: 'Bells on Fire',
    name: 'Bells on Fire',
    provider: 'amatic',
    providerGameId: '334',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/747_BellsOnFire.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4015ee60-81bc-4d71-8e36-d507897eb0de',
    slug: 'Grand Wild Dragon',
    name: 'Grand Wild Dragon',
    provider: 'amatic',
    providerGameId: '10501',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/grandwilddragon.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '2a9ea70c-9a50-4599-9c95-e290f9cbb12b',
    slug: 'Lady Fruits 100 Easter',
    name: 'Lady Fruits 100 Easter',
    provider: 'amatic',
    providerGameId: '8884',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LadyFruits100easter.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd65c3c3f-46a5-4c6a-99a2-bd51b4a77145',
    slug: 'Hottest Fruits 20',
    name: 'Hottest Fruits 20',
    provider: 'amatic',
    providerGameId: '8131',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/hottestfruits20.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f49a34a8-f599-46e4-adae-1583b701ef73',
    slug: 'Dragons Gift',
    name: 'Dragons Gift',
    provider: 'amatic',
    providerGameId: '6910',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/DragonsGift.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '501da6bc-1155-4e91-93d3-c5789108feef',
    slug: 'Hot Fruits 100',
    name: 'Hot Fruits 100',
    provider: 'amatic',
    providerGameId: '4582',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotFruits100.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4880dcf6-2402-41a9-b500-6b3d9b3303a7',
    slug: 'Golden Joker',
    name: 'Golden Joker',
    provider: 'amatic',
    providerGameId: '4265',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/GoldenJoker.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '10e009c5-ac53-42c1-89fb-1fce78324ebe',
    slug: 'La Gran Aventura',
    name: 'La Gran Aventura',
    provider: 'amatic',
    providerGameId: '3146',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LaGranAventura.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'cc7cd5e3-0ff8-4be5-8964-c0484542b729',
    slug: 'Big Panda',
    name: 'Big Panda',
    provider: 'amatic',
    providerGameId: '3066',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/867_BigPanda.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '319d25c5-6987-40f7-afb8-420c1f91b19e',
    slug: 'Book Of Aztec',
    name: 'Book Of Aztec',
    provider: 'amatic',
    providerGameId: '370',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/743_BookOfAztec.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '5cc60c14-8695-44fd-87da-570eb36c9979',
    slug: 'Cool Diamonds II',
    name: 'Cool Diamonds II',
    provider: 'amatic',
    providerGameId: '361',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/767_CoolDiamondsII.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '90294313-b9b4-4290-a68d-d77661f194b3',
    slug: 'Royal Unicorn',
    name: 'Royal Unicorn',
    provider: 'amatic',
    providerGameId: '351',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/779_RoyalUnicorn.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '36294143-4f2f-4fea-b42a-eaf15b9d7a95',
    slug: 'Hot Twenty',
    name: 'Hot Twenty',
    provider: 'amatic',
    providerGameId: '341',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/739_HotTwenty.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '9fc77bc5-0286-4552-a919-f5244f535a3c',
    slug: 'Eye of Ra',
    name: 'Eye of Ra',
    provider: 'amatic',
    providerGameId: '335',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/771_EyeOfRa.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f4c185f1-c001-43a1-b3d4-7355126b3045',
    slug: 'Lucky Double',
    name: 'Lucky Double',
    provider: 'amatic',
    providerGameId: '8888',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LuckyDouble.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8b7b19ed-e1ec-4d33-861b-b95ddc9cb858',
    slug: 'Lovely Lady Deluxe',
    name: 'Lovely Lady Deluxe',
    provider: 'amatic',
    providerGameId: '8886',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LovelyLadyDeluxe.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'b1a3804b-76b4-4ee1-bc5b-58aecc232962',
    slug: 'Harle Queen',
    name: 'Harle Queen',
    provider: 'amatic',
    providerGameId: '8878',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HarleQueen.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8b349ca3-518b-4798-b765-77919f0acd23',
    slug: 'Triple Wild',
    name: 'Triple Wild',
    provider: 'amatic',
    providerGameId: '8875',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/TripleWild.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c88df497-d340-4f97-81b8-1892e03058b1',
    slug: 'Double Diamonds',
    name: 'Double Diamonds',
    provider: 'amatic',
    providerGameId: '8872',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/DoubleDiamonds.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '55ec2a37-8880-4489-b7ec-0b54dcb4eac0',
    slug: 'Plenty Dragons',
    name: 'Plenty Dragons',
    provider: 'amatic',
    providerGameId: '6929',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/PlentyDragons.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '50e6b375-6df7-4efe-9017-056af27f057f',
    slug: 'Lucky Joker 100',
    name: 'Lucky Joker 100',
    provider: 'amatic',
    providerGameId: '6928',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LuckyJoker100.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '2682b740-d55e-46fe-a53f-76f8f9b2f467',
    slug: 'Book of Fruits',
    name: 'Book of Fruits',
    provider: 'amatic',
    providerGameId: '6911',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BookofFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '115466a7-530a-4ff6-bf15-d9457b6a246b',
    slug: 'Hot Choice Deluxe',
    name: 'Hot Choice Deluxe',
    provider: 'amatic',
    providerGameId: '6899',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotChoiceDeluxe.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8d3b9a02-7be8-474c-a0c1-5a32612e3e8b',
    slug: 'Black Jack',
    name: 'Black Jack',
    provider: 'amatic',
    providerGameId: '4612',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BlackJack.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'affe6cd8-259e-4d23-bf62-f1de0ad79c10',
    slug: 'Hot Fruits 20',
    name: 'Hot Fruits 20',
    provider: 'amatic',
    providerGameId: '4577',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotFruits20.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '100d7e35-384c-4489-aebd-edf11357b581',
    slug: 'Sakura Fruits',
    name: 'Sakura Fruits',
    provider: 'amatic',
    providerGameId: '4267',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/SakuraFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'a4eb444b-1b74-4fa2-b503-4f8d4792b9e0',
    slug: 'All Ways Joker',
    name: 'All Ways Joker',
    provider: 'amatic',
    providerGameId: '4214',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/AllWaysJoker.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'dc1a7e2e-d85d-4cce-bcfb-7ed68ea2aa8b',
    slug: 'Jacks Or Better',
    name: 'Jacks Or Better',
    provider: 'amatic',
    providerGameId: '3157',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/JacksOrBetter.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'bef37549-c2cb-43d9-9b4b-6463b5723bad',
    slug: 'All Ways Win',
    name: 'All Ways Win',
    provider: 'amatic',
    providerGameId: '3142',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/AllWaysWin.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'cc91e010-6aa6-4700-be8b-101f38e2b892',
    slug: 'Diamonds on Fire',
    name: 'Diamonds on Fire',
    provider: 'amatic',
    providerGameId: '3067',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/DiamondsOnFire.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c5e34510-17b3-4c0d-8983-be1294126018',
    slug: 'Aztec Secret',
    name: 'Aztec Secret',
    provider: 'amatic',
    providerGameId: '3065',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/AztecSecret.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ff32472b-0aa4-4a19-ba16-c98abfc75814',
    slug: 'Book of Fortune',
    name: 'Book of Fortune',
    provider: 'amatic',
    providerGameId: '371',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/742_BookOfFortune.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f5f0c02a-6115-4c13-9c30-d9fbaae8daeb',
    slug: 'Arising Phoenix',
    name: 'Arising Phoenix',
    provider: 'amatic',
    providerGameId: '367',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/774_ArisingPhoenix.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '439cb43a-8059-4b6b-833e-f3f2ad653d81',
    slug: 'All Ways Fruits',
    name: 'All Ways Fruits',
    provider: 'amatic',
    providerGameId: '359',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/766_AllwaysFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '750572a4-ec3b-4e4a-8d83-4b2d2fff461e',
    slug: 'Blue Dolphin',
    name: 'Blue Dolphin',
    provider: 'amatic',
    providerGameId: '355',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/355_Bluedolphin.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'abdeaee4-1ec4-41eb-a0e7-5aa3cd517b98',
    slug: 'Lucky Coin',
    name: 'Lucky Coin',
    provider: 'amatic',
    providerGameId: '348',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/759_LuckyCoin.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '1bcf188d-8b1e-4072-a064-e69a92a43f44',
    slug: 'Casanova',
    name: 'Casanova',
    provider: 'amatic',
    providerGameId: '347',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/763_Casanova.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'baf57153-7eb7-44d2-89da-03e312f2b309',
    slug: 'Merry Fruits',
    name: 'Merry Fruits',
    provider: 'amatic',
    providerGameId: '338',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/750_MerryFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4fbe3d16-3288-44a0-b022-caeaf0305552',
    slug: 'Billyonaire',
    name: 'Billyonaire',
    provider: 'amatic',
    providerGameId: '297',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/775_billyonaire.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8f7dcfb2-0b12-4a01-a4e2-4855e9aa09f0',
    slug: 'Double Diamonds 50',
    name: 'Double Diamonds 50',
    provider: 'amatic',
    providerGameId: '10500',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/DoubleDiamonds50.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '1b547b37-0b2f-4bf7-9d7a-0e20d239b2ba',
    slug: 'Billyonaire Bonus Buy',
    name: 'Billyonaire Bonus Buy',
    provider: 'amatic',
    providerGameId: '10499',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/billyonairebonusbuy.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '662a1e07-6df3-4360-b68c-3039b5fb5b8d',
    slug: 'Santas Fruits',
    name: 'Santas Fruits',
    provider: 'amatic',
    providerGameId: '8887',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/SantasFruits.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ba5af445-7393-4627-abcf-4e64260d82db',
    slug: 'Lady Fruits 20',
    name: 'Lady Fruits 20',
    provider: 'amatic',
    providerGameId: '8883',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LadyFruits20.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd5223fa6-78c7-4ac4-9258-4b21e1e89d52',
    slug: 'Burning Bells 10',
    name: 'Burning Bells 10',
    provider: 'amatic',
    providerGameId: '8876',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BurningBells10.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '875ac18d-4d62-42a8-8e0f-6da198b2025b',
    slug: 'Relic Riches',
    name: 'Relic Riches',
    provider: 'amatic',
    providerGameId: '8873',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/RelicRiches.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'e03808a2-e828-4750-8b6f-e0bb8627de6f',
    slug: 'Cash And Crab',
    name: 'Cash And Crab',
    provider: 'amatic',
    providerGameId: '8871',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/CashAndCrab.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'a9200d45-f00c-436a-81f2-d0a6b001644b',
    slug: 'Hot Fruits 27',
    name: 'Hot Fruits 27',
    provider: 'amatic',
    providerGameId: '7695',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotFruits27.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8dbc9d3c-e7f8-4b72-9acd-ed85ec80abd6',
    slug: 'Lucky Respin',
    name: 'Lucky Respin',
    provider: 'amatic',
    providerGameId: '6927',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LuckyRespin.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'b3e0997d-1748-48d8-b582-048d783e7332',
    slug: 'Nicer Dice 40',
    name: 'Nicer Dice 40',
    provider: 'amatic',
    providerGameId: '6926',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/NicerDice40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '771a22e1-818c-439e-a2f1-c3fb68487267',
    slug: 'Oktoberfest',
    name: 'Oktoberfest',
    provider: 'amatic',
    providerGameId: '6898',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/Oktoberfest.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ec558633-a7a1-4079-9cc9-9080e02f30d1',
    slug: 'Hot Fruits 40',
    name: 'Hot Fruits 40',
    provider: 'amatic',
    providerGameId: '6895',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotFruits40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '6d736b32-0d9c-406c-a254-408c4ecab81e',
    slug: 'Book of Fruits Halloween',
    name: 'Book of Fruits Halloween',
    provider: 'amatic',
    providerGameId: '6896',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BookofFruitsHalloween.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'e126e15f-dff6-4980-b0b2-449e914c8097',
    slug: 'Book of Lords',
    name: 'Book of Lords',
    provider: 'amatic',
    providerGameId: '4580',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BookofLords.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '969447ae-7258-4971-93dd-c3db796ef254',
    slug: 'Book of Queen',
    name: 'Book of Queen',
    provider: 'amatic',
    providerGameId: '4579',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BookofQueen.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'cc4df48a-baa0-4928-a1c2-6a2358aabfce',
    slug: 'Fruit Express',
    name: 'Fruit Express',
    provider: 'amatic',
    providerGameId: '4576',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/FruitExpress.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '18b8cbee-af5f-434d-aa89-4f31ee3cea38',
    slug: 'Kings Crown',
    name: 'Kings Crown',
    provider: 'amatic',
    providerGameId: '4216',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/KingsCrown.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c750e035-6859-4805-8047-95c41eaa7bf2',
    slug: 'Roulette Royal',
    name: 'Roulette Royal',
    provider: 'amatic',
    providerGameId: '3165',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/793_RouletteRoyal.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '7e497a00-8f72-48cb-9305-349490f35495',
    slug: 'Lucky Little Devil',
    name: 'Lucky Little Devil',
    provider: 'amatic',
    providerGameId: '4213',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames2/game_img_2/LuckyLittleDevil.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '57cfe654-0a05-4713-bb57-b14f38a0c176',
    slug: 'Lightning Hot',
    name: 'Lightning Hot',
    provider: 'amatic',
    providerGameId: '3144',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LightNingHot.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4d417dd7-463c-447d-ae84-53d18ed0f61b',
    slug: 'Magic Forest',
    name: 'Magic Forest',
    provider: 'amatic',
    providerGameId: '3098',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/787_MagicForest.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'e678c18d-7e12-4ac0-893c-834f3c58eefa',
    slug: 'Hot 81',
    name: 'Hot 81',
    provider: 'amatic',
    providerGameId: '3095',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/790_Hot81.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'db56ec09-b1ec-4df4-bdf1-1183070d6ea6',
    slug: 'Billys Game',
    name: 'Billys Game',
    provider: 'amatic',
    providerGameId: '3088',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BillysGame.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8754b41c-f58d-4253-a70e-ee65cdb51e23',
    slug: 'Golden Book',
    name: 'Golden Book',
    provider: 'amatic',
    providerGameId: '3063',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/791_GoldenBook.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f6c302bd-e8eb-46f4-99fc-9d2c91551c91',
    slug: 'Tweety Birds',
    name: 'Tweety Birds',
    provider: 'amatic',
    providerGameId: '3068',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/TweetyBirds.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f62a49af-7707-4445-a80d-090176abb82c',
    slug: 'Gem Star',
    name: 'Gem Star',
    provider: 'amatic',
    providerGameId: '3059',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/GemStar.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c06eeeeb-2308-40eb-bbd8-a8461b25e6fb',
    slug: 'Lady Joker',
    name: 'Lady Joker',
    provider: 'amatic',
    providerGameId: '369',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/369_LadyJoker.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd6c391ce-39b4-40c5-bf6c-9c897a2398de',
    slug: 'Wild Stars',
    name: 'Wild Stars',
    provider: 'amatic',
    providerGameId: '368',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/298_WildStars.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'de1db8e8-670e-4028-98be-80f5aab2fcd7',
    slug: 'Wild Respin',
    name: 'Wild Respin',
    provider: 'amatic',
    providerGameId: '366',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/770_WildRespin.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '07babdd1-36cc-4558-bf13-04dcb41517b6',
    slug: 'Party Time',
    name: 'Party Time',
    provider: 'amatic',
    providerGameId: '360',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/765_PartyTime.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ea565657-e579-47bd-83ce-e27043079b7b',
    slug: 'Wild Shark',
    name: 'Wild Shark',
    provider: 'amatic',
    providerGameId: '358',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/358_WildShark.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '091e9c2b-9ec4-4ad2-bcd6-44467a9806fe',
    slug: 'Magic Idol',
    name: 'Magic Idol',
    provider: 'amatic',
    providerGameId: '354',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/749_MagicIdol.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ce5e537d-efe5-4ab5-840c-6c236a95c093',
    slug: 'Magic Owl',
    name: 'Magic Owl',
    provider: 'amatic',
    providerGameId: '346',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/773_MagicOwl.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd80bd441-6796-4060-a2b0-3df7ea0d458d',
    slug: 'Hot Star',
    name: 'Hot Star',
    provider: 'amatic',
    providerGameId: '344',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/741_HotStar.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '65897f7f-23c4-4670-bda3-f19928f14744',
    slug: 'Lady Luck',
    name: 'Lady Luck',
    provider: 'amatic',
    providerGameId: '349',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/758_LadyLuck.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '865b4ffb-c098-493d-8c6e-c4119ad850e8',
    slug: 'Wolf Moon',
    name: 'Wolf Moon',
    provider: 'amatic',
    providerGameId: '337',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/768_Wolfmoon.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd809f952-91b9-40fd-9470-492d784fc1ea',
    slug: 'Grandx',
    name: 'Grandx',
    provider: 'amatic',
    providerGameId: '299',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/762_1064_grandx.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '097d7af2-3005-4917-ba03-30853dbe1938',
    slug: 'Double Joker 20',
    name: 'Double Joker 20',
    provider: 'amatic',
    providerGameId: '10496',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/doublejoker20.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd8406414-18e3-40e4-abef-07492ac172d5',
    slug: 'Hot Soccer',
    name: 'Hot Soccer',
    provider: 'amatic',
    providerGameId: '8879',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/HotSoccer.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '5691fc45-efef-4824-8a9e-3ed940cdc81f',
    slug: 'Lucky Joker 40',
    name: 'Lucky Joker 40',
    provider: 'amatic',
    providerGameId: '7698',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/LuckyJoker40.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'd080f500-932d-4e1f-980a-11ec7f566f0b',
    slug: 'Fortune Girl',
    name: 'Fortune Girl',
    provider: 'amatic',
    providerGameId: '6900',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/FortuneGirl2.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '0acdd8f0-06d2-4c3a-830b-b6305ab74535',
    slug: 'Beauty Fairy',
    name: 'Beauty Fairy',
    provider: 'amatic',
    providerGameId: '4578',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/BeautyFairy.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ae0d7469-2b29-4862-a1bf-c37857520ac5',
    slug: 'Flying Dutchman',
    name: 'Flying Dutchman',
    provider: 'amatic',
    providerGameId: '4215',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/FlyingDutchman.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'f99f1388-5317-4018-b072-f039efc5bee0',
    slug: 'Vampires',
    name: 'Vampires',
    provider: 'amatic',
    providerGameId: '3143',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/Vampires.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'c222cbfa-60ab-423b-b2ee-3044f4b7560c',
    slug: 'Fire and Ice',
    name: 'Fire and Ice',
    provider: 'amatic',
    providerGameId: '3087',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/FireandIce.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '229054c7-af63-48d8-868a-446368dc378c',
    slug: 'Bells on fire Rombo',
    name: 'Bells on fire Rombo',
    provider: 'amatic',
    providerGameId: '3029',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/785_BellsOnFireRombo.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '03aba125-d8f2-41ef-a3bf-f7654f95d533',
    slug: 'Admiral',
    name: 'Admiral',
    provider: 'amatic',
    providerGameId: '363',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/745_Admiral.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '4c3d1d3e-c081-4498-b45d-01947a68faca',
    slug: 'Mermaids Gold',
    name: 'Mermaids Gold',
    provider: 'amatic',
    providerGameId: '356',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/778_MermaidsGold.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: true,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: 'ff91e180-a9de-46d7-85ea-1dd00547f633',
    slug: 'Tiki Madness 100',
    name: 'Tiki Madness 100',
    provider: 'amatic',
    providerGameId: '10502',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/tikimadness100.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: false,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
  {
    id: '8e7a73aa-b79e-424e-b5eb-67d13e10b865',
    slug: 'Pharaohs Gold 20',
    name: 'Pharaohs Gold 20',
    provider: 'amatic',
    providerGameId: '8885',
    img: 'https://static.cdneu-stat.com/resources/sitepicstbs/slgames/game_img_2/PharaohsGold20.jpg',
    houseEdge: '3.00',
    rtp: '97.00',
    minBetUsd: '0.10',
    maxBetUsd: '1000.00',
    maxWinUsd: null,
    isActive: false,
    isDemoEnabled: true,
    categoriesLinks: [],
  },
];
export async function seedGames() {
  await db.insert(gamesTable).values(data);
  console.log('✅ Games seeded successfully');
  process.exit(2);
}

seedGames();
