'use client';

import HeaderUpGetbonus from '@/components/HeaderUp/HeaderUpGetbonus';
import Header from '@/components/Header/Header';
import SlideBar from '@/components/SlideBar/SlideBar';
import Footer from '@/components/Footer/Footer';
import Chat from '@/widgets/chat/ui';
import PartnersNavigation from '@/components/PartnersNavigation/PartnersNavigation'; 
import Accordion, { AccordionItemData } from '@/components/Accordion/Accordion';

import styles from './page.module.scss';

const faqData: AccordionItemData[] = [
    {
        id: 1,
        question: 'HOW DOES THE PARTNER PROGRAM WORK?',
        answer: 
            'Our partner program allows you to earn commissions by referring new players to our platform. ' +
            'After registration, you will receive a unique tracking link. \n' +
            'When a user clicks this link and registers, they are assigned to your account, and you receive a percentage of the revenue or a fixed payment for their activity.',
    },
    {
        id: 2,
        question: 'WHAT ARE THE AVAILABLE COMMISSION MODELS?',
        answer: 
            'We offer several flexible cooperation models to suit different types of traffic: \n' +
            '<ul>' +
            '<li><b>Revenue Share:</b> Earn a percentage of the net revenue generated by your players.</li>' +
            '<li><b>CPA (Cost Per Acquisition):</b> Get a fixed one-time payment for every player who makes a qualifying deposit.</li>' +
            '<li><b>Hybrid:</b> A combination of both CPA and Revenue Share models.</li>' +
            '</ul>' +
            'Contact your manager to discuss individual terms.',
    },
    {
        id: 3,
        question: 'WHEN AND HOW DO I GET PAID?',
        answer: 
            'Payments are processed automatically on a regular basis (usually monthly or bi-weekly). ' +
            'The minimum withdrawal amount is $100. \n' +
            'We support various payment methods including Bitcoin, Ethereum, USDT, and Bank Transfers. ' +
            'Make sure your payment details are correctly filled in the "Settings" section.',
    },
    {
        id: 4,
        question: 'WHAT MARKETING TOOLS DO YOU PROVIDE?',
        answer: 
            'In your dashboard, you will find a wide range of marketing materials to help you convert traffic: ' +
            '<ul>' +
            '<li>Direct tracking links and deep links to specific games.</li>' +
            '<li>High-quality animated and static banners in multiple languages.</li>' +
            '<li>Ready-made landing pages optimized for high conversion.</li>' +
            '<li>JSON/XML feeds for automatic data updates.</li>' +
            '</ul>',
    },
    {
        id: 5,
        question: 'ARE THERE ANY RESTRICTIONS ON TRAFFIC SOURCES?',
        answer: 
            'We accept most types of traffic, including SEO, PPC, social media, and streaming. However, the following are strictly prohibited: \n' +
            '<ul>' +
            '<li>Email spam or any form of unsolicited messaging.</li>' +
            '<li>Contextual advertising on brand keywords (Brand Bidding).</li>' +
            '<li>Creating "incentivized" traffic or misleading users.</li>' +
            '</ul>' +
            'Violation of these rules may lead to account suspension and forfeiture of commissions.',
    },
];

export default function AffiliateFAQPage() {
    return (
        <>
            <HeaderUpGetbonus />
            <Header />
            <div className={styles.wrapper}>
                <SlideBar />
                <main className={styles.mainContent}>
                    
                    <div className={styles.navContainer}>
                        <PartnersNavigation />
                    </div>

                    <section className={styles.faqSection}>
                        <h1 className={styles.title}>Partnership Program</h1>
                        <div className={styles.accordionWrapper}>
                            <Accordion items={faqData} />
                        </div>
                    </section>
                </main>
            </div>
            <Chat />
            <Footer />
        </>
    );
}